language: java
jdk:
  - oraclejdk8
install: 
    - ant clean
    - ant build
 
deploy:
  provider: releases
  api_key: scKFuytwDLrfjxqHQRqs 
  skip_cleanup: true
  all_branches: true
  on:
    tags: true 
 